import argparse
import os
import numpy as np
from mmengine import load
from pathlib import Path
from typing import List, Tuple, Union

# Optional: plotting
import matplotlib.pyplot as plt
from sklearn.metrics import multilabel_confusion_matrix, classification_report, average_precision_score

def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1 / (1 + np.exp(-x))

def to_np(x):
    # torch.Tensor to numpy
    if hasattr(x, "detach") and hasattr(x, "cpu"):
        return x.detach().cpu().numpy()
    return np.asarray(x)

def infer_num_classes_and_scores(results) -> Tuple[int, bool]:
    """Infer number of classes and whether pred_score looks like probabilities."""
    for r in results:
        ps = getattr(r, "pred_score", None) if not isinstance(r, dict) else r.get("pred_score", None)
        if ps is None:
            continue
        ps = to_np(ps).squeeze()
        if ps.ndim == 2:
            ps = ps[0]
        if ps.ndim == 1 and ps.size > 0:
            # Heuristic: if values are mostly in [0,1], treat as probabilities; otherwise logits
            is_prob_like = (ps.min() >= 0.0) and (ps.max() <= 1.0)
            return ps.size, is_prob_like
    raise RuntimeError("Cannot infer number of classes: no valid pred_score found.")

def to_indices(x) -> List[int]:
    """Convert different forms of gt/pred into index list."""
    if x is None:
        return []
    x = to_np(x)
    if x.ndim == 0:
        # Scalar -> single label index
        return [int(x)]
    if x.ndim == 1:
        # Could be index list (variable length) or multi-hot
        unique_vals = np.unique(x)
        if set(unique_vals.tolist()).issubset({0,1}) and x.size > 1 and x.sum() <= x.size:
            return np.where(x.astype(int) == 1)[0].tolist()
        else:
            return [int(i) for i in x.tolist()]
    if x.ndim == 2 and x.shape[0] == 1:
        return to_indices(x[0])
    return []

def to_multihot(indices: List[int], num_classes: int) -> np.ndarray:
    mh = np.zeros((num_classes,), dtype=np.int32)
    for i in indices:
        if 0 <= i < num_classes:
            mh[i] = 1
    return mh

def build_pred_from_score(pred_score: np.ndarray,
                          per_class_thr: Union[float, List[float]],
                          is_prob: bool) -> np.ndarray:
    """Convert pred_score (logits or prob) to multi-hot prediction."""
    scores = pred_score.copy()
    if not is_prob:
        scores = sigmoid(scores)
    scores = scores.reshape(-1)

    if isinstance(per_class_thr, (float, int)):
        thr = np.full_like(scores, float(per_class_thr))
    else:
        thr = np.asarray(per_class_thr, dtype=np.float32).reshape(-1)
        assert thr.size == scores.size, "per_class_thr length must equal num_classes"

    return (scores >= thr).astype(np.int32)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("results_pkl", type=str, help="Path to results.pkl generated by mmpretrain test")
    ap.add_argument("--out-dir", type=str, default=None, help="Output directory")
    ap.add_argument("--use_pred_score", action="store_true",
                    help="Use pred_score+thresholds to generate predictions (recommended for multi-label); otherwise use raw pred_label")
    ap.add_argument("--thr", type=float, default=0.5, help="Global threshold (probability domain)")
    ap.add_argument("--thr-per-class", type=str, default="",
                    help="Comma separated thresholds for each class, e.g. 0.6,0.4,0.5,... (overrides --thr)")
    ap.add_argument("--class-names", type=str, default="",
                    help="Comma separated class names (optional, for report/plot)")
    args = ap.parse_args()

    results = load(args.results_pkl)
    out_dir = args.out_dir or str(Path(args.results_pkl).with_suffix("").parent / "multilabel_analysis")
    os.makedirs(out_dir, exist_ok=True)

    num_classes, pred_is_prob = infer_num_classes_and_scores(results)

    class_names = None
    if args.class_names:
        class_names = [s.strip() for s in args.class_names.split(",")]
        assert len(class_names) == num_classes, "class_names length must equal num_classes"

    # Thresholds
    if args.thr_per_class:
        per_thr = [float(s) for s in args.thr_per_class.split(",")]
        assert len(per_thr) == num_classes, "thr-per-class length must equal num_classes"
    else:
        per_thr = float(args.thr)

    y_true = []
    y_pred = []

    for r in results:
        # Extract gt
        gt = r.get("gt_label", None) if isinstance(r, dict) else getattr(r, "gt_label", None)
        gt_idx = to_indices(gt)
        gt_mh = to_multihot(gt_idx, num_classes)

        if args.use_pred_score:
            # Use pred_score + thresholds to generate prediction
            ps = r.get("pred_score", None) if isinstance(r, dict) else getattr(r, "pred_score", None)
            if ps is None:
                # If no score, fallback to pred_label (rare)
                pl = r.get("pred_label", None) if isinstance(r, dict) else getattr(r, "pred_label", None)
                pred_idx = to_indices(pl)
                pred_mh = to_multihot(pred_idx, num_classes)
            else:
                ps = to_np(ps).squeeze()
                if ps.ndim == 2:
                    ps = ps[0]
                pred_mh = build_pred_from_score(ps, per_thr, is_prob=pred_is_prob)
        else:
            # Directly use pred_label (index list) -> multi-hot
            pl = r.get("pred_label", None) if isinstance(r, dict) else getattr(r, "pred_label", None)
            pred_idx = to_indices(pl)
            pred_mh = to_multihot(pred_idx, num_classes)

        y_true.append(gt_mh)
        y_pred.append(pred_mh)

    y_true = np.stack(y_true, axis=0)
    y_pred = np.stack(y_pred, axis=0)

    # Per-class binary confusion matrices
    cm = multilabel_confusion_matrix(y_true, y_pred)  # shape: [C, 2, 2]
    # Plot confusion matrix grid
    cols = min(4, num_classes)
    rows = int(np.ceil(num_classes / cols))
    plt.figure(figsize=(4*cols, 3.5*rows))
    for i in range(num_classes):
        tn, fp, fn, tp = cm[i].ravel()
        ax = plt.subplot(rows, cols, i+1)
        mat = np.array([[tn, fp],
                        [fn, tp]])
        im = ax.imshow(mat, interpolation="nearest")
        plt.colorbar(im, fraction=0.046, pad=0.04, ax=ax)
        title = class_names[i] if class_names else f"class {i}"
        ax.set_title(title)
        ax.set_xticks([0,1]); ax.set_xticklabels(["Pred 0","Pred 1"])
        ax.set_yticks([0,1]); ax.set_yticklabels(["True 0","True 1"])
        for (j,k), v in np.ndenumerate(mat):
            ax.text(k, j, str(int(v)), ha="center", va="center")
    plt.tight_layout()
    fig_path = os.path.join(out_dir, "confusion_matrix.png")
    plt.savefig(fig_path, dpi=200)
    print(f"[Saved] {fig_path}")

    # Classification report (multi-label)
    target_names = class_names if class_names else [f"class_{i}" for i in range(num_classes)]
    report = classification_report(y_true, y_pred, target_names=target_names, zero_division=0, output_dict=False)
    print(report)
    with open(os.path.join(out_dir, "classification_report.txt"), "w") as f:
        f.write(report)

    # Compute mAP (macro), based on probabilities (skip if using pred_label only)
    if args.use_pred_score:
        y_score = []
        for r in results:
            ps = r.get("pred_score", None) if isinstance(r, dict) else getattr(r, "pred_score", None)
            ps = to_np(ps).squeeze()
            if ps.ndim == 2:
                ps = ps[0]
            if not pred_is_prob:
                ps = sigmoid(ps)
            y_score.append(ps)
        y_score = np.stack(y_score, axis=0)
        ap_list = []
        for i in range(num_classes):
            ap = average_precision_score(y_true[:, i], y_score[:, i])
            ap_list.append(ap)
        map_macro = float(np.nanmean(ap_list))
        print(f"mAP (macro) = {map_macro:.4f}")
        with open(os.path.join(out_dir, "mAP_macro.txt"), "w") as f:
            f.write(f"{map_macro:.6f}\n")

if __name__ == "__main__":
    main()
